name: Await Check Suites
description: Wait for a commit's check suites to complete
author: Jitterbit, Inc.
branding:
  icon: 'watch'
  color: 'purple'
runs:
  using: node12
  main: dist/index.js
inputs:
  repository:
    description: >
      The commit's repository name with owner.
      For example, `jitterbit/await-check-suites`.
    required: true
    default: ${{ github.repository }}
  ref:
    description: >
      The commit's ref (can be a SHA, branch name, or a tag name).
    required: true
    default: ${{ github.sha }}
  token:
    description: >
      GitHub token for GitHub API requests.
      When `repository` is modified, set to a personal access token with access to `repository`.
    required: true
    default: ${{ github.token }}
  waitForACheckSuite:
    description: >
      Wait for a check suite to be created if none exist.
      This is important to protect against race conditions
      if you know a check suite should exist on the `ref`'s commit.
    required: true
    default: 'true'
  intervalSeconds:
    description: >
      Number of seconds to wait between checks.
    required: true
    default: '15'
  timeoutSeconds:
    description: >
      Number of seconds to wait before timing out.
    required: false
  failStepIfUnsuccessful:
    description: >
      Fail step if any of the check suites complete with a conclusion other than 'success'.
    required: true
    default: 'true'
  appSlugFilter:
    description: >
      Filter check suites for a particular app's slug (e.g., 'github-actions').
    required: false

outputs:
  conclusion:
    description: >
      The combined conclusion of all check suites.
